services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: usercv
      POSTGRES_PASSWORD: Nvquyen@123
      POSTGRES_DB: cvscanner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://usercv:Nvquyen%40123@db:5432/cvscanner
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  pgdata:
